
import type { Metadata } from "next";

import "./globals.css";

import Header from "@/components/header/header";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

import { QueryProvider } from "@/providers/queryProvider";


// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export const metadata: Metadata = {
  title: "Estoque Inteligente",
  description: "Sistema de gerenciamento inteligente de componentes eletrônicos",
  icons: {
    icon: "/ei.png",
    shortcut: "/ei.png",
    apple: "/ei.png",
  },
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className="flex justify-center"
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <main className="w-[100%]">
          <QueryProvider>
            {children}
          </QueryProvider>
        </main>
      </body>
    </html>
  );
}
